#!/usr/bin/env python3
"""
Normalize the 7 chosen clay-duck pose frames for the v3 single-pose duck
engine (bead asn-q3r): alpha-bbox crop each source pose, scale every duck to
an IDENTICAL pixel height, and bottom-center-anchor all of them on a shared
square canvas.

Why: the 7 poses were picked from `design/clay-poses/` (49 frames), each
generated by an independent AI render call. They are not pixel-continuous
with each other -- different renders put the duck at different sizes and
vertical offsets within the 1024x1024 source frame. Swapping directly
between two such frames makes the duck visibly jump in scale/position when
the app crossfades between states. Cropping to the alpha bbox, scaling every
crop to the same height, and bottom-anchoring on a common canvas removes
that jump: only the pose itself changes between frames, not the duck's
apparent size or footing.

Usage:
    python3 normalize_poses.py --out-dir /path/to/app/src/main/res/drawable-nodpi
"""

import argparse
import sys
from pathlib import Path

from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
POSES_DIR = SCRIPT_DIR.parent

CANVAS_SIZE = 512    # matches the app's existing drawable-nodpi bundling convention
TARGET_HEIGHT = 432  # duck's alpha-bbox height on the shared canvas
BOTTOM_MARGIN = 24   # px from the canvas bottom edge to the duck's bbox bottom

# (source pose in design/clay-poses/, output asset filename, DuckFrame token)
FRAMES = [
    ("08-listening-intro-01.png", "duck_attentive.png", "ATTENTIVE"),
    ("48-sleeping-01.png", "duck_sleep.png", "SLEEP"),
    ("23-thinking-01.png", "duck_think.png", "THINK"),
    ("05-blink-01.png", "duck_blink.png", "BLINK"),
    ("16-head-turn-02.png", "duck_nod.png", "NOD"),
    ("46-hand-raise-eager-01.png", "duck_raise_hand.png", "RAISE_HAND"),
    ("41-notes-scribble-01.png", "duck_write.png", "WRITE"),
]


def normalize(
    src_path: Path,
    canvas_size: int = CANVAS_SIZE,
    target_height: int = TARGET_HEIGHT,
    bottom_margin: int = BOTTOM_MARGIN,
) -> Image.Image:
    img = Image.open(src_path).convert("RGBA")
    bbox = img.getbbox()
    if bbox is None:
        raise ValueError(f"{src_path}: fully transparent, no alpha bbox found")

    cropped = img.crop(bbox)
    scale = target_height / cropped.height
    new_w = max(1, round(cropped.width * scale))
    resized = cropped.resize((new_w, target_height), Image.LANCZOS)

    canvas = Image.new("RGBA", (canvas_size, canvas_size), (0, 0, 0, 0))
    x = (canvas_size - new_w) // 2
    y = canvas_size - bottom_margin - target_height
    # Plain paste, no mask: canvas is fully transparent outside the paste
    # region, so a direct 4-channel copy is correct and, unlike
    # paste(resized, box, resized) -- using resized's own alpha as a blend
    # mask -- doesn't attenuate the low-alpha antialiased edge rows/columns
    # enough to fall out of a later getbbox() alpha threshold.
    canvas.paste(resized, (x, y))
    return canvas


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", required=True, help="directory to write the 7 normalized app-ready PNGs into")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for src_name, out_name, token in FRAMES:
        src = POSES_DIR / src_name
        if not src.exists():
            print(f"FAIL: source pose not found: {src}", file=sys.stderr)
            return 1
        canvas = normalize(src)
        out_path = out_dir / out_name
        canvas.save(out_path)
        bbox = canvas.getbbox()
        rows.append((token, src_name, out_name, bbox))

    heights = {bbox[3] - bbox[1] for _, _, _, bbox in rows}
    bottoms = {bbox[3] for _, _, _, bbox in rows}

    for token, src_name, out_name, bbox in rows:
        print(f"{token:11s} {src_name:28s} -> {out_name:20s} bbox={bbox} height={bbox[3] - bbox[1]}")

    if len(heights) != 1 or len(bottoms) != 1:
        print(f"FAIL: normalization did not produce identical height/bottom across all frames: heights={heights} bottoms={bottoms}", file=sys.stderr)
        return 1

    print(f"\nAll {len(rows)} frames normalized to height={heights.pop()}px, bottom anchor y={bottoms.pop()}px on a {CANVAS_SIZE}x{CANVAS_SIZE} canvas.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
